version: '2.3'

services:
  web:
    build: .
    ports:
      - "8888:80"
    volumes:
      - ".:/var/www/html:ro"
      - "./assembly_uploads:/var/www/html/assembly_uploads:rw"
      - "./study_uploads:/var/www/html/study_uploads:rw"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    healthcheck:
      test: mysqladmin ping -h localhost
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: dbCuratorTools
    volumes:
      - "./documentation/dbSNPs.sql:/docker-entrypoint-initdb.d/dbSNPs.sql:ro"
