version: '2.3'

services:
  web:
    image: bitnami/php-fpm:7.4-prod
    environment:
      PHP_CLI_SERVER_WORKERS: 4
      CURATORTOOLS_MAX_CONCURRENT_REQUESTS: 4
      CURATORTOOLS_INSERT_BATCH_SIZE: 100
      CURATORTOOLS_LOOP_INTERVAL: 100
      CURATORTOOLS_SNP_CHUNK_SIZE: 100
      MYSQL_HOST: 'localhost'
      MYSQL_DATABASE: 'dbCuratorTools'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
    ports:
      - "8080:8080"
    user: daemon
    entrypoint: php -S 0.0.0.0:8080 -c /opt/bitnami/php/etc/php.ini-development -d pdo_mysql.default_socket=/run/mysqld/mysqld.sock
    volumes:
      - ".:/app:ro"
      - "./documentation/php-snpcurator.ini:/opt/bitnami/php/etc/conf.d/php-snpcurator.ini:ro"
      - "./assembly_uploads:/app/assembly_uploads:rw,delegated"
      - "./study_uploads:/app/study_uploads:rw,delegated"
      - mysqld-sock:/run/mysqld
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: dbCuratorTools
# unsafe (but performant) developer configuration
# RPM-based distributions put mysql socket file in /var/lib/mysql by default
    command: >-
      --socket=/run/mysqld/mysqld.sock
      --innodb-checksum-algorithm=none
      --innodb-flush-method=nosync
      --innodb-flush-log-at-trx-commit=0
      --innodb-log-file-size=2G
      --skip-innodb-doublewrite
      --skip-log-bin
      --slow_query_log
    volumes:
      - "./documentation/dbSNPs.sql:/docker-entrypoint-initdb.d/dbSNPs.sql:ro"
      - mysqld-sock:/run/mysqld

volumes:
  mysqld-sock:
